openapi: 3.0.1
info:
  title: Renewable Updates API
  version: "1.0.0"
paths:
  /get-latest-summary:
    get:
      summary: Get the latest summary
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Summary of latest renewable updates
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
servers:
  - url: https://your-api-url.onrender.com